mail:
  retriever_method: imap
  user_name: username@gmail.com
  password: password
  address: imap.gmail.com
  port: 993
  enable_ssl: true
credentials:
  username: xxx
  password: xxx
mailgun:
  api_key: api_key
